pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        mavenCentral()
    }
}

rootProject.name = 'sitm-mio-speed'

include 'shared'
include 'v1-monolithic'
include 'v2-threadpool'
include 'v3-distributed'
include 'visualizer-client'
